---
abstract: 'A searchable sotre backed by MongoDB'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Store-MongoDB
provides:
  Catmandu::Store::MongoDB:
    file: lib/Catmandu/Store/MongoDB.pm
    version: 0.03
  Catmandu::Store::MongoDB::Bag:
    file: lib/Catmandu/Store/MongoDB/Bag.pm
    version: 0
  Catmandu::Store::MongoDB::Searcher:
    file: lib/Catmandu/Store/MongoDB/Searcher.pm
    version: 0
requires:
  Catmandu: 0.01
  MongoDB: 0.503003
  Moo: 1.000008
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
