---
abstract: 'A searchable store backed by MongoDB'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-Store-MongoDB
provides:
  Catmandu::Store::MongoDB:
    file: lib/Catmandu/Store/MongoDB.pm
    version: '0.0302'
  Catmandu::Store::MongoDB::Bag:
    file: lib/Catmandu/Store/MongoDB/Bag.pm
  Catmandu::Store::MongoDB::Searcher:
    file: lib/Catmandu/Store/MongoDB/Searcher.pm
requires:
  Catmandu: '0.01'
  MongoDB: '0.503003'
  Moo: '1.000008'
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: '0.0302'
