---
abstract: 'A searchable store backed by MongoDB'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Module::Build: '0.3601'
  Software::License: '0.103010'
  Test::Exception: '0.32'
  Test::More: '1.001003'
  Test::Pod: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-Store-MongoDB
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9205'
  MongoDB: v0.705.0.0
  Moo: '1.006000'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Store-MongoDB/issues
  homepage: https://github.com/LibreCat/Catmandu-Store-MongoDB
  repository: https://github.com/LibreCat/Catmandu-Store-MongoDB.git
version: '0.0303'
x_contributors:
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
